# Generated by Django 5.0 on 2023-12-23 14:37

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('auth_code', models.CharField(blank=True, default='12345678', max_length=32, null=True, verbose_name='Authorization code')),
                ('view_my_info', models.BooleanField(default=False, verbose_name='Viewing personal information')),
                ('surname', models.CharField(blank=True, max_length=32, null=True, verbose_name='Surname')),
                ('b_day', models.DateTimeField(blank=True, null=True, verbose_name='Birthday')),
                ('sex', models.IntegerField(choices=[(0, 'woman'), (1, 'man'), (2, 'undefined')], default=2)),
                ('m_mailing', models.BooleanField(default=False, verbose_name='Mailing')),
                ('view_counter', models.IntegerField(default=0, verbose_name='Profile views')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Ad created at..')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Ad title')),
                ('text', models.TextField(verbose_name='Ad context')),
                ('category', models.CharField(choices=[('tanks', 'Танки'), ('heals', 'Хилы'), ('dd', 'ДД'), ('buyers', 'Торговцы'), ('gld_masters', 'Гилдмастеры'), ('qst_givers', 'Квестгиверы'), ('smiths', 'Кузнецы'), ('tanners', 'Кожевники'), ('ptn_brewers', 'Зельевары'), ('spl_masters', 'Мастера заклинаний')], default='tanks', max_length=32, verbose_name='Ad category')),
                ('last_edit_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Ad last edit')),
                ('view_counter', models.IntegerField(default=0, verbose_name='Ad views')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adboard.author', verbose_name='Ad author')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=255, verbose_name='Response content')),
                ('last_edit_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Last edited response')),
                ('hidden', models.BooleanField(default=False, verbose_name='Response visibility')),
                ('status', models.IntegerField(choices=[(0, 'Just exists'), (1, 'Is read'), (2, 'Accepted'), (-1, 'Rejected')], default=0, verbose_name='Response status')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adboard.ad', verbose_name='Response to ad')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adboard.author', verbose_name='Response author')),
            ],
        ),
    ]
